# Generated by Django 5.0.6 on 2024-06-04 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(default='')),
                ('is_complete', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.ManyToManyField(to='categoryApp.categorymodel')),
            ],
        ),
    ]
